# don't store production credentials
version: '3.1'

services:

  sannev:
    build: .
    container_name: sannev_wp
    restart: always
    depends_on:
      - db
    networks:
      - wp-network
    ports:
      - 8001:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dev_user_sannev
      WORDPRESS_DB_PASSWORD: supersecret
      WORDPRESS_DB_NAME: wp_dev_sannev

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    networks:
      - wp-network
    environment:
      MYSQL_DATABASE: wp_dev_sannev
      MYSQL_USER: dev_user_sannev
      MYSQL_PASSWORD: supersecret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
    driver: local

networks:
  wp-network: