# don't store production credentials
version: '3.1'

services:

  wordpress:
    build: .
    image: trao/wordpress
    container_name: wordpress
    restart: always
    networks:
      - wp-network
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dev_user
      WORDPRESS_DB_PASSWORD: supersecret
      WORDPRESS_DB_NAME: wp_dev

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    networks:
      - wp-network
    environment:
      MYSQL_DATABASE: wp_dev
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: supersecret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-volume:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    networks:
      - wp-network
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 80:80
      - 443:443

  certbot:
    networks:
      - wp-network
    container_name: letsencrypt_certbot
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  db-volume:
    driver: local

networks:
  wp-network: