version: '3.7'

services:
  wp_sanne:
    image: wordpress:latest
    environment:
      - WORDPRESS_VERSION=latest
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DATA_DIR=/wordpress
    ports:
      - 4000:80

  mysql:
    image: mariadb:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    networks:
      - wp_sanne_net
    restart: always

volumes:
  wp_sanne_data:
    name: wp_sanne_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/wordpress