# don't store production credentials
version: '3.7'

services:
  sanne:
    build: .
    container_name: sannev_wp
    restart: always
    networks:
      - proxy_nginx
    ports:
      - 8001:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: sannedb
      WORDPRESS_DB_PASSWORD: 'super_secret'

networks:
  proxy_nginx:
    external: true