version: '3'
services:
  wordpress:
    build: .
    ports:
      - "8000:80"
    links:
      - wordpress_db:mysql
    environment:
      WORDPRESS_DB_PASSWORD: qwerty
  wordpress_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: