# don't store production credentials
version: '3.1'

services:

  wordpress:
    build: .
    image: trao/wordpress
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dev_user
      WORDPRESS_DB_PASSWORD: supersecret
      WORDPRESS_DB_NAME: wp_dev

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wp_dev
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: supersecret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
    driver: local