version: '3.6'
services:

  wp_sanne:
    image: wordpress:${WP_SANNE_VERSION}
    container_name: wp_sanne
    volumes:
      - ${WP_SANNE_DATA_DIR}:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WP_SANNE_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WP_SANNE_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WP_SANNE_DB_HOST}
      - WORDPRESS_DB_USER=${WP_SANNE_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_SANNE_DB_PASSWORD}
    networks:
      - reverse_proxy
    restart: always

networks:
  reverse_proxy:
    external: true