version: '3.6'
services:

  wp_sanne:
    image: wordpress:${WORDPRESS_VERSION}
    container_name: wp_sanne
    volumes:
      - wp_sanne_data:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    networks:
      - wp_sanne_net
    restart: always

networks:
  wp_sanne_net:
    name: wp_sanne_net

volumes:
  wp_sanne_data:
    name: wp_sanne_data